displayName: "footyai-training"
jobSpec:
  workerPoolSpecs:
  - machineSpec:
      machineType: "n1-standard-4"
      acceleratorType: "NVIDIA_TESLA_T4"
      acceleratorCount: 1
    replicaCount: 1
    containerSpec:
      imageUri: "gcr.io/learnagentspace/footyai-training"
      env:
      - name: "GCS_BUCKET"
        value: "footyai"
      - name: "GCS_PROJECT" 
        value: "learnagentspace"